### PR TITLE
Ngfw 14101 prompted for password remote

### PR DESCRIPTION
**Pull request by john-phillips-arista**
Fix for NGFW 14101 with some unit testing. There were some python2 - 3 errors.

### CODE REVIEW

**Comment by john-phillips-arista** [comment]
The git history is screwed up here, not sure why.

**Comment by john-phillips-arista** [comment]
@jsommerville-untangle Do we also want to change the 'AuthRequest' header here?

**Review by sdelafond — APPROVED** [review]
LGTM.

**Review by dhadarau — APPROVED** [review]
Good

**Pull request merged**
