### PR TITLE
ngfw-14700: Remove Facebook Authenticator

### PR DESCRIPTION
**Pull request by singhrohit23**
Removed Facebook authentication references from UI, Captive Portal.
Removed Testcase related to Facebook authentication.

After testing the PR, Facebook as a authentication is removed from Captive portal.
Screenshot from 2024-07-23 14-29-33

### CODE REVIEW

**Review by mayur-dhande — APPROVED** [review]

**Comment by cblaise-untangle** [comment]
We need to change existing customers who happen to be using FACEBOOK to ANY_OAUTH.  Use the settings upgrade pattern for this.

**Comment by singhrohit23** [comment]
> We need to change existing customers who happen to be using FACEBOOK to ANY_OAUTH. Use the settings upgrade pattern for this.
@cblaise-untangle 


Added support for changing Authentication type to ANY_OAUTH from Facebook for existing customers.

Modified test case of Facebook, (if facebook is set as authentication type, it will be changed to ANY_OAUTH)
Following are screenshots
Screenshot from 2024-07-24 13-48-09

**Comment by mayur-dhande** [comment]
@singhrohit23 shouldn't we deprecate `FACEBOOK` enum from `CaptivePortalSettings` ?
```
    public static enum AuthenticationType
    {
        NONE, LOCAL_DIRECTORY, RADIUS, ACTIVE_DIRECTORY, ANY_DIRCON, GOOGLE,
        /**
         * @deprecated Use {@link AuthenticationType#ANY_OAUTH} instead.
         */
        @Deprecated
        FACEBOOK,
        MICROSOFT, ANY_OAUTH, CUSTOM, ANY
    };

**Comment by singhrohit23** [comment]
> @singhrohit23 shouldn't we deprecate `FACEBOOK` enum from `CaptivePortalSettings` ?
> 
> ```
>     public static enum AuthenticationType
>     {
>         NONE, LOCAL_DIRECTORY, RADIUS, ACTIVE_DIRECTORY, ANY_DIRCON, GOOGLE,
>         /**
>          * @deprecated Use {@link AuthenticationType#ANY_OAUTH} instead.
>          */
>         @Deprecated
>         FACEBOOK,
>         MICROSOFT, ANY_OAUTH, CUSTOM, ANY
>     };
> ```

We need to chec

> @singhrohit23 shouldn't we deprecate `FACEBOOK` enum from `CaptivePortalSettings` ?
> 
> ```
>     public static enum AuthenticationType
>     {
>         NONE, LOCAL_DIRECTORY, RADIUS, ACTIVE_DIRECTORY, ANY_DIRCON, GOOGLE,
>         /**
>          * @deprecated Use {@link AuthenticationType#ANY_OAUTH} instead.
>          */
>         @Deprecated
>         FACEBOOK,
>         MICROSOFT, ANY_OAUTH, CUSTOM, ANY
>     };
> ```

Done

**Review by cblaise-untangle — APPROVED** [review]

**Pull request merged**
